# config file
# 
# contains basic configuration settings and such

# database settings
---

db_user: root
db_password: ''
db_host: localhost
db_database: branch

# a random salting string. Eventually, when this config file gets 
# generated in the install, this should be done by that, and not
# by hand. For now, just pick some random string. It'll be fun, I
# promise...
salt: branchSalt_$@?!=/>wordup
